
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AddBranchDrugs extends javax.swing.JFrame {

    /**
     * Creates new form AddBranchDrugs
     */
    public AddBranchDrugs() {
        initComponents();
        setTableDetails();
    }
    
    DefaultTableModel model;
    
    public void addingDrugToBranch(){
        String branchName = txt_branchName.getText();
        String drugName = txt_drugName.getText();
        String category = txt_drugCateg.getText();
        
        try{
            Connection con = DBConnection.getConnection();
            
            String Sql1 = "SELECT * FROM " + branchName + " WHERE drugName=?";
            PreparedStatement pst1 = con.prepareStatement(Sql1);
            pst1.setString(1, drugName);
            ResultSet rs = pst1.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "This drug already exists!");
            }else{
            
            
            String sql ="insert into " +branchName+ " (drugName, category) Values (?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, drugName);
            pst.setString(2, category);
            int rowcount = pst.executeUpdate();
            
            if(rowcount > 0){
                
                JOptionPane.showMessageDialog(this, "Drug Successfully Created in " +branchName+ " branch");
            }else{
                JOptionPane.showMessageDialog(this, "An error occured while trying to create drug!");
            } 
            }
        }catch(Exception e){
            e.printStackTrace();
        }    
    }
    public void setTableDetails(){
       
        String branchName = txt_branchName.getText();
        
       if (!branchName.isEmpty()) {
        try{
           Connection con = DBConnection.getConnection();
           PreparedStatement st = con.prepareStatement("SELECT * FROM " + branchName);
           ResultSet rs = st.executeQuery("select * from " + branchName);
           
           while (rs.next()){
               String drugId = rs.getString("drugId");
               String drugName = rs.getString("drugName");
               String category = rs.getString("category");
               String quantity = rs.getString("drugQuantity");
               
               Object [] obj = {drugId, drugName, category, quantity};
               model = (DefaultTableModel)branchDrugsTable.getModel();
               model.addRow(obj);
               
           }
       }catch(Exception e){
        e.printStackTrace();
    }
    }
    }
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) branchDrugsTable.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_branchName = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_drugName = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        branchDrugsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_drugCateg = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter Branch Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        txt_branchName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_branchName.setPlaceholder("Enter Branch Name");
        txt_branchName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_branchNameFocusLost(evt);
            }
        });
        getContentPane().add(txt_branchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel6.setText("Enter Drug Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 30));

        txt_drugName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_drugName.setPlaceholder("Enter Drug Name");
        txt_drugName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_drugNameFocusLost(evt);
            }
        });
        txt_drugName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drugNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_drugName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("create drug");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText("Back");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        branchDrugsTable.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        branchDrugsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug_id", "DrugName", "Category", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        branchDrugsTable.setGridColor(new java.awt.Color(0, 204, 204));
        branchDrugsTable.setRowHeight(30);
        branchDrugsTable.setShowGrid(true);
        branchDrugsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                branchDrugsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(branchDrugsTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 900, 490));

        jLabel7.setText("Enter Drug Category");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 30));

        txt_drugCateg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_drugCateg.setPlaceholder("Enter Drug Category");
        txt_drugCateg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_drugCategFocusLost(evt);
            }
        });
        txt_drugCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drugCategActionPerformed(evt);
            }
        });
        getContentPane().add(txt_drugCateg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, 30));

        setSize(new java.awt.Dimension(1470, 754));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_branchNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_branchNameFocusLost
        clearTable();
        setTableDetails();
    }//GEN-LAST:event_txt_branchNameFocusLost

    private void txt_drugNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_drugNameFocusLost
        
    }//GEN-LAST:event_txt_drugNameFocusLost

    private void txt_drugNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drugNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drugNameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        welcomePage welcome = new welcomePage();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void branchDrugsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchDrugsTableMouseClicked

    }//GEN-LAST:event_branchDrugsTableMouseClicked

    private void txt_drugCategFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_drugCategFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drugCategFocusLost

    private void txt_drugCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drugCategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drugCategActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txt_branchName.getText().equals("") &&(!txt_drugName.getText().equals(""))){
        addingDrugToBranch();
        }else{
            JOptionPane.showMessageDialog(this, "please fill in all fields");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBranchDrugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBranchDrugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBranchDrugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBranchDrugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBranchDrugs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable branchDrugsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private app.bolivia.swing.JCTextField txt_branchName;
    private app.bolivia.swing.JCTextField txt_drugCateg;
    private app.bolivia.swing.JCTextField txt_drugName;
    // End of variables declaration//GEN-END:variables
}
