
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class BranchRecords extends javax.swing.JFrame {

    /**
     * Creates new form BranchRecords
     */
    public BranchRecords() {
        initComponents();
        joinBranchRecordsToTable();
    }
    DefaultTableModel model;

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void joinBranchRecordsToTable(){
    
        try{
            Connection con = DBConnection.getConnection();
            java.sql.Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT drugId, drugName, category, drugQuantity, 'cbd' AS branch FROM cbd " +
                "UNION " +
                "SELECT drugId, drugName, category, drugQuantity, 'kilimani' AS branch FROM kilimani " +
                "UNION " +
                "SELECT drugId, drugName, category, drugQuantity, 'karen' AS branch FROM karen " +
                "UNION " +
                "SELECT drugId, drugName, category, drugQuantity, 'meru' AS branch FROM meru " +
                "UNION " +
                "SELECT drugId, drugName, category, drugQuantity, 'chuka' AS branch FROM chuka");
            
            while (rs.next()){
                String drugIds = rs.getString("drugId");
                String names = rs.getString("drugName");
                String branch = rs.getString("branch");
                String categs = rs.getString("category");
                String quantitys = rs.getString("drugQuantity");
                
                Object[] obj = {drugIds, names, branch, categs, quantitys};
            model = (DefaultTableModel)branchRecordTable.getModel();
            model.addRow(obj);
                
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
}
    public void clearTable(){
        DefaultTableModel model = (DefaultTableModel) branchRecordTable.getModel();
        model.setRowCount(0);
    }
    public void searchMethod(){
        String branchName = txt_branchSearch.getText();
        String drugName = txt_drugSearch.getText();
        String category = txt_drugSearch.getText();
        
        try{
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM " + branchName + " WHERE drugName = ? OR category = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1, drugName);
            pst.setString(2, category);
            
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String drugIds = rs.getString("drugId");
                String drugNames = rs.getString("drugName");
                String branchNames = rs.getString("branchName");
                String categorys = rs.getString("category");
                String quantitys = rs.getString("drugQuantity");
                
                Object[] obj = {drugIds, drugNames, branchNames, categorys, quantitys};
            model = (DefaultTableModel) branchRecordTable.getModel();
            model.addRow(obj);           
            }
                     
        }catch (Exception e){
            e.printStackTrace();
    }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        branchRecordTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_drugSearch = new app.bolivia.swing.JCTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_branchSearch = new app.bolivia.swing.JCTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 1010, 80));

        branchRecordTable.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        branchRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug_id", "Name", "Branch", "Category", "Quantity"
            }
        ));
        branchRecordTable.setGridColor(new java.awt.Color(0, 204, 204));
        branchRecordTable.setRowHeight(30);
        branchRecordTable.setShowGrid(true);
        branchRecordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                branchRecordTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(branchRecordTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 1010, 190));

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel5.setText("Search");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 60, 30));

        txt_drugSearch.setBackground(new java.awt.Color(204, 204, 204));
        txt_drugSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_drugSearch.setPlaceholder("Name / Category");
        getContentPane().add(txt_drugSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 220, -1));

        jLabel21.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/search.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, 30, 30));

        txt_branchSearch.setBackground(new java.awt.Color(204, 204, 204));
        txt_branchSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 0, 153)));
        txt_branchSearch.setPlaceholder("Branch Name");
        getContentPane().add(txt_branchSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 220, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton4.setText("view All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1414, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void branchRecordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_branchRecordTableMouseClicked

    }//GEN-LAST:event_branchRecordTableMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        if (txt_drugSearch.getText().equals("") || txt_branchSearch.getText().equals("")){
         JOptionPane.showMessageDialog(this, "Please fill both fields");
        }else{
            clearTable();
            searchMethod();
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        clearTable();
        joinBranchRecordsToTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        welcomePage welcome = new welcomePage();
        welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BranchRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BranchRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BranchRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BranchRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BranchRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable branchRecordTable;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private app.bolivia.swing.JCTextField txt_branchSearch;
    private app.bolivia.swing.JCTextField txt_drugSearch;
    // End of variables declaration//GEN-END:variables
}
